package com.revature.beans;

public enum Conditions {

	BLINDED,CHARMED,DEAFENED,FATIGUED,FRIGHTENED, GRAPPLED, INCAPACITATED, INVISIBLE,
	PARALYZED, PETRIFIED, POISONED, PRONE,RESTRAINED, STUNNED, UNCONCIOUS, EXAUSTION
	
}
