DROP TABLE EMPLOYEE;
/
DROP TABLE DEPARTMENT;
/
CREATE TABLE EMPLOYEE( 
EMPLOYEE_ID INTEGER PRIMARY KEY,
EMP_FIRSTNAME VARCHAR2(100),
EMP_LASTNAME VARCHAR2(100),
DEPARTMENT_ID INTEGER,
SALARY NUMBER(10,2),
EMP_EMAIL VARCHAR2(100)
);
/
CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INTEGER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(100)
);
/
DROP SEQUENCE SQ_CHALLENGE_EMPLOYEE_PK;
/
DROP SEQUENCE SQ_DEPARTMENT_PK;
/
CREATE SEQUENCE SQ_CHALLENGE_EMPLOYEE_PK
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE SQ_DEPARTMENT_PK
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER TR_INSERT_CHALLENGE_EMPLOYEE
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_CHALLENGE_EMPLOYEE_PK.NEXTVAL 
    INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TR_INSERT_DEPARTMENT
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    SELECT SQ_DEPARTMENT_PK.NEXTVAL
    INTO :NEW.DEPARTMENT_ID FROM DUAL;
END;
/
INSERT INTO EMPLOYEE(Emp_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('Dave','Brown',1,100000,'davebrown@gmail.com');
/
INSERT INTO EMPLOYEE(Emp_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('Bill','Red',2,101000,'billred@gmail.com');
/
INSERT INTO EMPLOYEE(Emp_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('Larry','Green',3,101100,'larrygreen@gmail.com');
/
INSERT INTO EMPLOYEE(Emp_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('Tony','Purple',1,120000,'tonypurple@gmail.com');
/
INSERT INTO EMPLOYEE(Emp_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('Blane','Beige',2,200000,'blanebeige@gmail.com');
/
INSERT INTO EMPLOYEE(Emp_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('King','Blanco',3,110000,'kingblanco@gmail.com');
/
INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES('HUMAN RESOURCES');
/
INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES('MARKETING');
/

INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES('SALES');
/
SELECT *
FROM EMPLOYEE;
/
SELECT *
FROM DEPARTMENT;
/